FROM python:3.6.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt
ADD . /code/


RUN python backend/dockeranalyser/manage.py collectstatic --noinput
#RUN python backend/dockeranalyser/manage.py migrate

EXPOSE 8000
