# crawler image based on python
FROM python:alpine

RUN mkdir /code

WORKDIR /code

COPY crawler/  /code/
RUN pip install -r requirements.txt

ENTRYPOINT ["python","/code/entryCrawler.py" ]
CMD ["--help"]
