# crawler image based on python
FROM  python:3.6.6

RUN mkdir /code

WORKDIR /code

COPY crawler/  /code/
RUN pip install -r requirements.txt

ENTRYPOINT ["python","/code/entryCrawler.py" ]
CMD ["--help"]
