#scanner image
FROM python

#  DEPLOY_PACKAGE_PATH: contains the path of the deploy folder (default deploy-package)
ARG DEPLOY_PACKAGE_PATH=./deploy-package/

RUN mkdir /code

WORKDIR /code

COPY  analysis/pyFinder/requirements.txt /code/

RUN pip install  -r requirements.txt

COPY analysis/pyFinder/ /code

RUN echo "Deploy package: $DEPLOY_PACKAGE_PATH"
COPY "$DEPLOY_PACKAGE_PATH" /code/pyfinder/deploy

RUN pip install -r /code/pyfinder/deploy/requirements.txt

ENTRYPOINT ["python","/code/entryScanner.py"]
CMD ["--help"]
