#scanner image
FROM python

RUN mkdir /code

WORKDIR /code

COPY  pyFinder/requirements.txt /code/

RUN pip install  --upgrade pip
RUN pip install -r requirements.txt

# ADD . /code/

COPY pyFinder/ /code

#deploy-package is the folder given by an user with the custom analysis function
COPY deploy-package-graph/ /code/pyfinder/deploy

RUN pip install -r /code/pyfinder/deploy/requirements.txt

ENTRYPOINT ["python","/code/entryScanner.py"]
CMD ["--help"]
